name: 'Setup Kubeconfig'
description: 'Setup Kubeconfig for an EKS cluster'
inputs:
  cluster-name:
    description: 'EKS cluster name'
    required: true
  cluster-region:
    description: 'EKS cluster region'
    required: true
  account-id:
    description: 'The AWS account id where the cluster is'
    required: true
  role-name:
    description: 'The name of the AWS role to assume'
    required: true

runs:
  using: "node12"
  main: "dist_main/index.js"
  post: "dist_cleanup/index.js"
